name: Build Status

on: [push, pull_request]

jobs:
  build:
    name: make
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.13
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make
